version: '3.9'

services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: payment-service-dev
    ports:
      - "3006:3006"
    environment:
      PORT: 3006
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis-payment
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      VIETQR_ACCOUNT_NO: ${VIETQR_ACCOUNT_NO}
      VIETQR_ACQ_ID: ${VIETQR_ACQ_ID}
      VIETQR_ACCOUNT_NAME: ${VIETQR_ACCOUNT_NAME}
      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE}
      VNPAY_HASH_SECRET: ${VNPAY_HASH_SECRET}
      VNPAY_URL: ${VNPAY_URL}
      IMAP_HOST: ${IMAP_HOST}
      IMAP_PORT: ${IMAP_PORT}
      IMAP_USER: ${IMAP_USER}
      IMAP_PASS: ${IMAP_PASS}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true

